### ISSUE TITLE
tide times when on vacation

### ISSUE THREAD

**Issue by edif30** [edif30/home-assistant-config#100]

**Comment by edif30** [comment]
```
sensor:
  - platform: worldtidesinfo
    api_key: !secret world_tides_api_key
    latitude: '39.308'
    longitude: '-74.533'
```
