### ISSUE TITLE
Days since sensor

### ISSUE THREAD

**Issue by edif30** [edif30/home-assistant-config#71]
```
sensor:
  - platform: template
    sensors:
      christmas_timer:
        friendly_name: "Days since christmas"
        unit_of_measurement: 'Days'
        value_template: "{{ relative_time(strptime('2017-12-24-+0100', '%Y-%m-%d-%z')) }}"
```
